### ISSUE TITLE
CSS wrapping bug in Comments section on iPhone

### ISSUE THREAD

**Issue by kevinkuebler** [shanselman/hanselman.com-bugs#1]
Noticed this CSS issue with the comments section when viewing a post on an iPhone.
![Screenshot 2020-10-13 at 9 15 49 AM](https://user-images.githubusercontent.com/95889/95865907-347d8080-0d35-11eb-9ff6-b0f48a697313.png)

**Comment by shanselman** [comment]
Fixed with flex box
