### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by amilcar-calles** [shanselman/hanselman.com-bugs#11]
Right now this image works just fine

https://hanselmanblogcontent.azureedge.net/Windows-Live-Writer/553ffddd97b6_E720/image_7.png 

a few minutes ago didn't, it redirected to some strange like this:

https://microsoftsto.112.2o7.net/b/ss/msstoextblogs1/1/H.20.3/s79214190451688?AQB=1&pccr=true&vidn=2FC530E905158DDB-60000B1F4CAB7643&ndh=1&t=16/9/2020%2022%3A15%3A25%205%20300&ns=microsoftsto&pageName=www.hanselman.com/blog/&g=https%3A//www.hanselman.com/blog/&cc=USD&s=1920x1080&c=24&j=1.6&v=N&k=Y&bw=442&bh=554&p=Microsoft%20Edge%20PDF%20Plugin%3BMicrosoft%20Edge%20PDF%20Viewer%3BNative%20Client%3B&pe=lnk_e&pev1=https%3A//hanselmanblogcontent.azureedge.net/Windows-Live-Writer/553ffddd97b6_E720/image_7.png&pid=www.hanselman.com/blog/&pidt=1&oid=https%3A//hanselmanblogcontent.azureedge.net/Windows-Live-Writer/553ffddd97b6_E720/image_7.png&ot=A&AQE=1

**Comment by shanselman** [comment]
Hm...I'll watch this but I can't repro, trying many days
