### ISSUE TITLE
Typo: Homepage, Speakers section

### ISSUE THREAD

**Issue by PureKrome** [shanselman/hanselman.com-bugs#12]
Hi @shanselman 

(I hope this is where we post typo's, not just bug's..)

quick typo fix here:

`Azrue` (wrong) ▶️ `Azure` (correct)

ref:
![image](https://user-images.githubusercontent.com/899878/96685459-daca2580-13c8-11eb-99ee-4ab91a3bdd37.png)

Cheers! Keep fighting the good fight!

**Comment by shanselman** [comment]
Thanks! Fixed!
