### ISSUE TITLE
Browsing through archive

### ISSUE THREAD

**Issue by fmfernandes** [shanselman/hanselman.com-bugs#14]
Not a "bug" per se but on the archive [page](https://www.hanselman.com/blog/archive/2020/12) the navigation arrows next to the month/year name looks different. Next month is `❯` while previous month is the simple `<` symbol. Also happens in the "complete" year overview, like [here](https://www.hanselman.com/blog/archive/2020)

**Comment by shanselman** [comment]
Nice one!
