### ISSUE TITLE
Image broken/missing in latest post

### ISSUE THREAD

**Issue by FizzBuzz791** [shanselman/hanselman.com-bugs#18]
Reading this [post](https://www.hanselman.com/blog/using-the-aspnet-core-environment-feature-to-manage-development-vs-production-for-any-config-file-type) (great, as always) and the image for the Azure App Service Config blade seems to be broken.

This is the image: [https://hanselmanblogcontent.azureedge.net/Windows-Live-Writer/d28f743b2166_D2D7/image_571da71c-8bc1-4e3c-a54a-f069624bf597.png](https://hanselmanblogcontent.azureedge.net/Windows-Live-Writer/d28f743b2166_D2D7/image_571da71c-8bc1-4e3c-a54a-f069624bf597.png) - it can't even be opened directly.

**Comment by shanselman** [comment]
Try again? Hiccup?
