### ISSUE TITLE
A semi colon is appearing at the end of comments

### ISSUE THREAD

**Issue by kent13** [shanselman/hanselman.com-bugs#2]
On this page accouncin the change there are many comments.
https://www.hanselman.com/blog/migrating-this-blog-to-azure-its-done-now-the-work-begins

All the comments end with a Semi-Colon.;

Felix reported it in the comments but did not submit an issue.

Unless of course every one comments is a programmer and are ending their logical unit! ;   ;-)

**Comment by shanselman** [comment]
Nice! Fixed.
