### ISSUE TITLE
Correct README.md

### ISSUE THREAD

**Issue by ghost** [shanselman/hanselman.com-bugs#24]
> Recently it moved from being:
> a 13 year old .NET Framework app on ASP.NET and a Windows Server on real metal hardware
to
> a fresh and new .NET Core app forked and improved by Mark Downie https://github.com/poppastring/dasblog-core and running under Linux on Azure!

Now that's wrong:

![image](https://user-images.githubusercontent.com/67918878/99653195-bf614180-2a7e-11eb-9447-304b20a98706.png)

/cc @shanselman

**Comment by shanselman** [comment]
What's wrong?

**Comment by ghost** [comment]
It's now just .NET

**Comment by shanselman** [comment]
Doh! Thanks! @alannt777

**Comment by ghost** [comment]
BTW, it seems that you forgot to fix it

**Comment by shanselman** [comment]
Ah, thanks, but the blog is still 3.1. The home page at / and the podcast are .net 5
