### ISSUE TITLE
Comment on this post [0]

### ISSUE THREAD

**Issue by MichelCollard** [shanselman/hanselman.com-bugs#26]
Hi!

Every blog post on the https://www.hanselman.com/blog/ page shows "Comment on this post [0]".

**Comment by shanselman** [comment]
Weird, that's new. Good bug! Thanks! @poppastring

**Comment by poppastring** [comment]
@shanselman 

Here are a couple examples taghelper you should be using:
`<post-comment-link post="@Model" />`
`<post-comment-link post="@Model" link-text="Comments [{0}]" />`

Could you possibly send your `_BlogItem.cshtml` file directly to me? 

It still makes no sense why it works on the individual pages. Caching issue? Do you have "Enable front page caching" enabled?
My hypothesis is that we are not breaking the cache when people add comments, maybe switch off caching.

**Comment by shanselman** [comment]
I'm using      

`<comment-post post="@Model"></comment-post>`

I'll try that other one! Yes, caching is one. This worked a few months ago.

**Comment by shanselman** [comment]
Weird...I did a full site restart and it works. Weird cache perhaps.
