### ISSUE TITLE
Broken link to Google Play podcast

### ISSUE THREAD

**Issue by fernandogmo** [shanselman/hanselman.com-bugs#29]
tl;dr:
Suggested fix: https://podcasts.google.com/feed/aHR0cHM6Ly9mZWVkcy5zaW1wbGVjYXN0LmNvbS9ndnR4VWlJZg

Context:
The link to the Google Play page for Hanselminutes is currently broken.

Current broken link: https://play.google.com/music/listen?u=0#/ps/Ixvhlgjbehlg2ipt76p7yvppsfy
which redirects to: https://music.youtube.com/googleplaymusic#/ps/Ixvhlgjbehlg2ipt76p7yvppsfy
which notifies user that: "**Google Play Music is no longer available**".

Suggested fix: https://podcasts.google.com/feed/aHR0cHM6Ly9mZWVkcy5zaW1wbGVjYXN0LmNvbS9ndnR4VWlJZg

**Comment by shanselman** [comment]
Thanks!
