### ISSUE TITLE
Broken link on the bottom of "Do they deserve the gift of your keystrokes?"

### ISSUE THREAD

**Issue by 99littlebugs** [shanselman/hanselman.com-bugs#33]
Hey friend, 

There's a broken link on the bottom of [Do they deserve the gift of your keystrokes?](https://www.hanselman.com/blog/do-they-deserve-the-gift-of-your-keystrokes) where it points to [32 ways to make your blog suck less](https://www.hanselman.com/suckless)

**Comment by shanselman** [comment]
Good bug, thanks!!
