### ISSUE TITLE
Comments area of blog doesn't respect dark mode

### ISSUE THREAD

**Issue by DaveDustin** [shanselman/hanselman.com-bugs#34]
When I finished scrolling to the bottom of your latest blog post, I was blinded by the comments section coming into view.

Running Windows 10 (21390.2025), Edge Dev (Version 95.0.1011.1 (Official build) dev (64-bit))

![image](https://user-images.githubusercontent.com/12723166/134095634-c499a2c8-7fbc-4d1b-90c8-87ebdf140fff.png)

**Comment by shanselman** [comment]
Fixed, try a ctrl-f5 @DaveDustin ?

**Comment by DaveDustin** [comment]
All good now..
