### ISSUE TITLE
Footer link broken

### ISSUE THREAD

**Issue by fmfernandes** [shanselman/hanselman.com-bugs#4]
I dunno if it has something to do with the recent update on your blog but on the footer we can see 

![image](https://user-images.githubusercontent.com/24195829/95927882-6115b480-0d96-11eb-8557-03c2d6f17802.png)

and that `-e "20201013.2\n302"` seems strange. I'm pretty sure I clicked on it sometime ago and it worked fine... Now it goes to a 401 page. Hope it helps!

**Comment by shanselman** [comment]
Nice one! Thanks!

**Comment by fmfernandes** [comment]
Hey, @shanselman, if I may, I also noticed that the "Greates Hits" link on the footer, first column is also broken! :)

**Comment by shanselman** [comment]
This one? https://www.hanselman.com/blog/GreatestHits.aspx

**Comment by fmfernandes** [comment]
Haha. Yep! Pretty sure it was a 404
