### ISSUE TITLE
Newsletter link

### ISSUE THREAD

**Issue by fmfernandes** [shanselman/hanselman.com-bugs#5]
Inside the "About Scott" section on the bottom of every post, the link to your wonderful newsletter is broken. It's [https://www.hanselman.com/newsletter](https://www.hanselman.com/newsletter), with the last forward slash it works fine [https://www.hanselman.com/newsletter/](https://www.hanselman.com/newsletter/).

Maybe it should work both ways? :)

**Comment by shanselman** [comment]
```    
   <rule name="newsletter" patternSyntax="ExactMatch" stopProcessing="true">
      <match url="newsletter" />
      <action type="Redirect" url="newsletter/" redirectType="Found" />
    </rule>
```
