### ISSUE TITLE
life as a diabetic link broken

### ISSUE THREAD

**Issue by mmiller314** [shanselman/hanselman.com-bugs#6]
I'm currently receiving a 404 error when clicking on the "life as a diabetic" link under "about me".

![image](https://user-images.githubusercontent.com/16403770/96014607-31a18f00-0e0c-11eb-9bf5-1e70ae426abd.png)

**Comment by shanselman** [comment]
Thanks!

**Comment by shanselman** [comment]
Adding a redirect
