### ISSUE TITLE
Older Posts Page Displays Comments Section & Comment Form

### ISSUE THREAD

**Issue by kashifkhan** [shanselman/hanselman.com-bugs#7]
When you visit https://www.hanselman.com/blog, posts show up with the comment count at the end of every post. The comment section & form is not visible.

If you visit a page thats is not the main one, such as https://www.hanselman.com/blog/page/1, the comment section and the comment submission form is no longer hidden. It displays all the comments for every post on that post list vs showing them only when you visit the page for that specific post.

![Screenshot 2020-10-15 at 10 33 15 AM](https://user-images.githubusercontent.com/361477/96152253-f7022a00-0ed1-11eb-90b5-8bbf92ad396b.png)

**Comment by shanselman** [comment]
GREAT bug! Thanks @kashifkhan!

**Comment by shanselman** [comment]
Fixed, will roll out soon.
