### ISSUE TITLE
Hanselman.com Is Not Redirecting to Https URL Consistently

### ISSUE THREAD

**Issue by kashifkhan** [shanselman/hanselman.com-bugs#8]
Typing hanselman.com in the browser doesn't auto-direct to the https endpoint. Once I typed in https://hanselman.com it works fine after that. 

I have seen this in Chrome (Incognito and Regular mode ) & Firefox (both modes) on Android, Chrome and Safari on iOS and then again on ChromeOS. Here are screenshots from Firefox & Chrome on Android

My Windows machine ( where I regularly read your blog ) is redirecting fine

![Firefox Android](https://user-images.githubusercontent.com/361477/96201261-c0ec9680-0f21-11eb-977f-fefe921d7752.png)

![Chrome Android](https://user-images.githubusercontent.com/361477/96201262-c21dc380-0f21-11eb-9d7f-4273567ae5c7.png)

**Comment by fmfernandes** [comment]
I think it may have something to do with `www`. Typing `hanselman.com` doesn't go to https, but `www.hanselman.com` works fine with https.

**Comment by shanselman** [comment]
I think it works now? :shipit:

**Comment by shanselman** [comment]
Try in Incognito?

**Comment by kashifkhan** [comment]
Just tried this in incognito on FF, Chrome on Android & ChromeOS. Working perfectly now

**Comment by shanselman** [comment]
Yay! Thanks for your help!
