### ISSUE TITLE
Blog posts duplication on frontpage

### ISSUE THREAD

**Issue by teilin** [shanselman/hanselman.com-bugs#9]
Blog posts duplicates on frontpage?

<img width="507" alt="Skjermbilde 2020-10-16 kl  08 24 05" src="https://user-images.githubusercontent.com/311637/96220518-2758cf80-0f89-11eb-8863-2fd864307baa.png">

**Comment by covamalia** [comment]
This also duplicated in the RSS feed: http://feeds.hanselman.com/ScottHanselman

![image](https://user-images.githubusercontent.com/9821870/96225552-2758cf80-0f89-11eb-863d-2026edfd968f.png)

**Comment by shanselman** [comment]
Awesome! Great bug thanks! :shipit:
